### ISSUE TITLE
Generation QIR from QuTiP not working

### ISSUE THREAD

**Issue by PariaNaghavi** [qutip/qutip-qip#188]
To provide an example for generating qir from qutip, I have been referring to the [documentations](https://qutip-qip.readthedocs.io/en/latest/qip-simulator.html?highlight=qir#import-and-export-quantum-circuits); However, I encountered some issues. Specifically, it appears that the current version of qutip-qip (0.3.0) does not provide access to the `.qir` attribute nor the `circuit_to_qir` function. When attempting to import the [qir.py](https://github.com/qutip/qutip-qip/blob/master/src/qutip_qip/qir.py) locally, it is missing dependency on `pyqir.parser` which is gone in the current version of pyqir (0.7.0). This may be due to version incompatibility between the two libraries with the recent updates. 
Next, I adjusted the code to use the `pyqir-generator` instead of the parser, but I reached the following error about SNOT gate “not implemented in the QIR base profile and may require a custom declaration".

**To replicate:** Please see [here](https://github.com/PariaNaghavi/qir-book/blob/main/qir-book/tutorials/qir-emission/qutip/qir-gen.ipynb)
**Current outcome:** An error due to missing `.qir` attribute and `circuit_to_qir` function in qutip-qip version and the missing dependency `pyqir.parser`
**Expected outcome:** To generate qir, as shown in [docs](https://qutip-qip.readthedocs.io/en/latest/qip-simulator.html?highlight=qir#import-and-export-quantum-circuits)
**Notes:** I would appreciate any suggestions or insights that might help in addressing these issues. Please let me know if there is any additional information or assistance that I can provide to fix this issue.
**Environment:**
QuTiP-QIP version: 0.0.3
pyqir version: 0.7.0
Python version: 3.9

_Originally posted by @PariaNaghavi in https://github.com/qutip/qutip-qip/issues/125#issuecomment-1382605820_

**Comment by BoxiLi** [comment]
Hi @PariaNaghavi 

Sorry for the delay.

Two points:
- pyqir 0.7 merges pyqir-generator, pyqir-parser so now they are all in one package `pyqir`. This means that the importation in `qir.py` needs to be updated according. Use `from pyqir import ...` for everything. You kind of already solved this problem.
- The remaining error is because of `from qutip.qip.circuit import QubitCircuit, Measurement, Gate`. You are mixing the new package `qutip_qip` and the old module in the qutip main package `qutip.qip`. Although they share many similarities. They are not the same. Because you imported `Gate` from `qutip.qip`. They code in `qir.py` cannot recognize it. Please use `from qutip_qip.circuit import QubitCircuit, Measurement, Gate` instead.

**Comment by BoxiLi** [comment]
@cgranade Is it ok to drop the support of `0.6` and only support `0.7`? Or should we try to keep it working both for `0.7` and `0.6`? It seems quite cumbersome to support both because it is not just a change of version but rather the packages `pyqir-generator` and `pyqir-parser` are replaced by `pyqir`.

**Comment by PariaNaghavi** [comment]
Thank you @BoxiLi. 
- Although ‘from pyqir import generator` works, I can not import the parser by `from pyqir import parser`. Please see the [issue](https://github.com/qir-alliance/pyqir/issues/229).
- Thanks for the hint on importing `qutip_qip.circuit`. I could try that on the `qir.py` file, once the parser is importable.

**Comment by BoxiLi** [comment]
With these changes (https://github.com/BoxiLi/qutip-qip/commit/d24b7b6c60a680644ec0f10dc775373bde1f2788) on `qir.py` and replacing `qutip.qip` with `qutip_qip`. I'm able to run through your `ipynb`.

**Comment by PariaNaghavi** [comment]
Thank you for the updates to the file. 
When I attempted to execute the updated `qir.py` file, I encountered an import error for `Measurement` from `qutip_qip.operations`.  Any hints on how I can resolve this? 
![Screen Shot 2023-01-18 at 18 30 02](https://user-images.githubusercontent.com/76576654/213341437-b92c947b-9023-4418-8d0e-7c2eecd1b803.png)

**Comment by BoxiLi** [comment]
You might be using an old version of the source code, not the one on the current master branch?

You can try
 `from qutip_qip.circuit import Measurement, Gate`.

**Comment by PariaNaghavi** [comment]
It works. Thank you!
Just a gentle follow up, would you consider pushing the changes in `qir.py?` on main?

**Comment by BoxiLi** [comment]
Yes, will soon make a PR on that.

**Comment by BoxiLi** [comment]
@cgranade Hi, could you maybe help us get the test updated for the new `pyqir`? I can get the code to work in (https://github.com/BoxiLi/qutip-qip/commit/d24b7b6c60a680644ec0f10dc775373bde1f2788) but have quite some difficulties updating the tests. It seems that the whole test file needs to be restructured because of the new interface?

**Comment by BoxiLi** [comment]
QIR support has been removed
