### ISSUE TITLE
Pulse class: consider changing description or code refactoring

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-qip#98]
It has been brought up that the `Pulse` class can be confusing for the user, as it brings together control pulses, the relative Hamiltonian, and noise added to the control pulses. This issue is opened to discuss this point and see what action to take. 

 There is also some conceptual overlap between `qutip-qip.Pulse` and `qutip.QobjEvo` (and `qutip.Qobj` for the time-constant part).

Right now the `Pulse` class is also discussed in https://qutip-qip.readthedocs.io/en/latest/qip-processor.html#modelling-quantum-hardware-with-processor. 

The actions to be taken can be discussed here, for example:
- A. Code refactoring. 
- B. Remove pulse from the public APIs
- C. Reframing the presentation of `Pulse` in the documentation (and white paper)

**Comment by BoxiLi** [comment]
My preferred solution would be:
- Add a `Model` class that represents the Hamiltonian model in `Processor` (see below).
- Bring the introduction of `Pulse` a bit down as an advanced use, both in the paper and in the tutorial. Phrase it as a data class rather than focusing too much on the concepts. It is different from `QobjEvo` because it separates noise from the ideal dynamics. And it needs to handle concatenation of coefficients, which is not a problem of `QobjEvo`.

The biggest problem I see is that the list of `Pulse` is partially initialized at the initialization of a `Processor` (including only the Hamiltonians, no `coeff`), which is indeed a less-optimal design. So I suggest to add a `Model` class that contains only Hamiltonian information. The class takes the hardware parameters to initialize
```
class Model():
    def __init__(params):
        ...

model = SpinChainModel({"h":0.01, ...})
```
and has a `__call__' that returns the corresponding Hamiltonian.
The Hamiltonian Qobj can be obtained by
```
model("sx0")
```
or whatever identifier that matches the implementation of the class, i.e.
```
model("sx", 0)
```

Advantages are:
- Hamiltonian models are now generated separately, there is not need for a partially initialized `Pulse`.
- There is no need to list all possible Hamiltonians ahead, which may take lots of memory for all-connected systems like ion trap or atoms.

@nathanshammah @quantshah Any opinions?
